In [1]:
# !pip install tensorflow

In [2]:
import tensorflow as tf
import numpy as np

In [7]:
# 텐서 생성
a = tf.constant(3)
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [8]:
# 랭크메서드
tf.rank(a)  # numpy : 0 -> 0차원 (스칼라값)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [9]:
# 리스트로 텐서객체 생성
b = tf.constant([1,2,3])   # shape : (3,) -> 3행 1열
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [10]:
tf.rank(b) # numpy : 1 -> 1차원

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [11]:
# print를 하면 numpy값이 맨 앞에 출력됨
print(tf.rank(b))

tf.Tensor(1, shape=(), dtype=int32)


In [12]:
# 튜플도 가능
c = tf.constant(((1,2), (3,4)))
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [18]:
# numpy array 도 가능
d = tf.constant(np.array([[1,2,3], [4,5,6]]))
d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [19]:
# 차원
d.shape

TensorShape([2, 3])

In [20]:
# 타입
d.dtype

tf.int32

In [22]:
# 타입 변환
# 정수 -> 실수
e = tf.cast(d, dtype=tf.float32)  # float/tf.float32 둘 다 사용 가능
e

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [24]:
# 텐서 생성할 때 타입 지정
e = tf.constant(np.array([[1,2,3], [4,5,6]]), dtype=tf.float32)
e

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [25]:
# numpy array로 변환
e.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [28]:
# 2.x 버전 변경 사항
# 기본연산 (텐서플로에서 사칙연산을 사용할 일은 별로 없음)
a = tf.constant(30)
b = tf.constant(10)

c = tf.add(a, b) # 더하기
d = tf.subtract(a,b) # 빼기
e = tf.multiply(a,b) # 곱하기
f = tf.divide(a, b) # 나누기
(c, d, e, f)

(<tf.Tensor: shape=(), dtype=int32, numpy=40>,
 <tf.Tensor: shape=(), dtype=int32, numpy=20>,
 <tf.Tensor: shape=(), dtype=int32, numpy=300>,
 <tf.Tensor: shape=(), dtype=float64, numpy=3.0>)

In [29]:
# 1차원 배열
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
tf.add(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [30]:
# 브로드캐스팅
a = tf.constant([1, 2, 3])
b = tf.constant(3)
tf.add(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>