### numeric + python
- 숫자와 관련된 작업 도구
- numpy array 자료형 : 파이썬의 리스트와 유사
- 리스트는 자료형 제한없음, array는 동일한 자료형만 가능
- 리스트보다 코드량도 적고, 속도도 빠름

In [2]:
import numpy as np

In [4]:
plist = [1,2,3]    # 리스트
# array로 변환
arr = np.array(plist)
arr

array([1, 2, 3])

In [5]:
# ndarray : n-dimension array
type(arr)

numpy.ndarray

In [6]:
# 모양
arr.shape

(3,)

In [12]:
# 2차원 2행, 3열
[
    [1,2,3],
    [4,5,6]
]
arr = np.array([[1,2,3],[4,5,6]])
arr.shape    # 행, 열

(2, 3)

In [14]:
# 개수
arr.size

6

#### numpy array 생성방법

In [16]:
# 1. 리스트를 변환 (상단에서 했음)
# 2. 동일한 값으로 생성
arr = np.full(10, 7)
arr

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [25]:
# 3. 모든 값이 0으로 생성
# arr = np.full(5,0)
arr = np.zeros(10, dtype=int)
arr
arr = np.zeros((5,2), dtype=int)    # 5행 2열
arr

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [27]:
# 4. 모든 값이 1로 생성
arr = np.ones((5,2), dtype=int)
arr

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [15]:
# 5. 랜덤값으로 생성
np.random.random(10)    # 0~1 사이의 실수를 뽑아줌
np.random.randint(1,7, size=(2,5))

array([[4, 3, 5, 4, 4],
       [5, 5, 4, 5, 5]])

In [7]:
# 6. 범위값으로 생성
np.arange(10)
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

#### 인덱싱 / 슬라이싱

In [8]:
arr = np.arange(1,20,3)
arr

array([ 1,  4,  7, 10, 13, 16, 19])

In [9]:
# 인덱싱
arr[0], arr[-1]

(1, 19)

In [11]:
# 인덱스 각각
# 1번, 3번
arr[[1,3]]

array([ 4, 10])

In [20]:
# 슬라이싱
arr[1:4]  # 1부터 4 전까지
arr[:4]   # 맨 앞에서부터 4 전까지
arr[3:]   # 3부터 맨 끝까지
arr[:]    # 맨 앞에서부터 맨 끝까지
arr[::2]  # 맨 앞에서부터 맨 끝까지 2개 요소마다

array([ 1,  7, 13, 19])

In [22]:
arr2 = np.array([1,2,3,'4',5,6])
arr2  # 하나라도 문자열이 섞여있으면 전체가 문자열이 됨 (동일한 자료형이어야 해서..)

array(['1', '2', '3', '4', '5', '6'], dtype='<U11')

#### 연산

In [23]:
arr1 = np.arange(10)
arr2 = np.arange(10, 20)

In [26]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# 모든 요소에 +1
# 1이 [1,1,1,1,1,1,1,1,1,1] 변환해서 연산 -> 브로드캐스팅
# 요소개수가 다르면 연산이 안됨
arr1 + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr1 + np.ones(10, dtype=int)  # 개수가 다르면 연산이 안됨

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr1 * 2    # 브로드캐스팅

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
arr1 + arr2   # 브로드캐스팅

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [34]:
arr1 * arr2   # 브로드캐스팅

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [44]:
# 퀴즈
dollar = [5000, 4000, 3500, 6000, 4500]
# for문 사용하지 않고, 원화로 변환(환율은 1400원)
np.array(dollar)* 1400

array([7000000, 5600000, 4900000, 8400000, 6300000])

In [54]:
# bool 연산
arr1 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

#### bool 연산 단계

In [50]:
arr2 % 3 == 0

array([False, False,  True, False, False,  True, False, False,  True,
       False])

In [51]:
# 조건에 만족하는 인덱스
np.where(arr2 % 3 == 0)

(array([2, 5, 8], dtype=int64),)

In [52]:
f = np.where(arr2 % 3 == 0)
arr2[f]

array([12, 15, 18])

In [53]:
arr2[np.where(arr2 % 3 == 0)]

array([12, 15, 18])

In [55]:
arr2[[2,5,8]]

array([12, 15, 18])

### 속도 비교

In [57]:
# 파이썬 리스트
import time

In [62]:
arr = np.arange(100000000)
start = time.time()
arr2 = arr * 1400
end = time.time()
print(end - start)

0.15711307525634766
