In [ ]:
# 시리즈 변수

In [2]:
import pandas as pd
리스트변수 = ['홍길동', '이순신', '유관순', '윤봉길']
시리즈변수 = pd.Series(리스트변수)
type(시리즈변수)

pandas.core.series.Series

In [5]:
시리즈변수

0    홍길동
1    이순신
2    유관순
3    윤봉길
dtype: object

In [8]:
# 데이터프레임
import pandas as pd
리스트변수 = (['홍길동', 29, '여'], ['이순신', 24, '남'],
                ['유관순', 38, '남'], ['윤봉길', 31, '여'])
# '리스트변수'를 데이터프레임 타입으로 변경하여 '데이터프레임변수'에 저장하기
데이터프레임변수 = pd.DataFrame(리스트변수)
type(데이터프레임변수)

pandas.core.frame.DataFrame

In [9]:
데이터프레임변수

0   1  2
0  홍길동  29  여
1  이순신  24  남
2  유관순  38  남
3  윤봉길  31  여

In [15]:
데이터프레임변수.index = ['1번', '2번', '3번', '4번']
데이터프레임변수

0   1  2
1번  홍길동  29  여
2번  이순신  24  남
3번  유관순  38  남
4번  윤봉길  31  여

In [17]:
데이터프레임변수.columns = ['이름', '나이', '성별']
데이터프레임변수

이름  나이 성별
1번  홍길동  29  여
2번  이순신  24  남
3번  유관순  38  남
4번  윤봉길  31  여

In [18]:
# '데이터프레임변수'에서 '나이' 열의 데이터만 가져오기
데이터프레임변수['나이']

1번    29
2번    24
3번    38
4번    31
Name: 나이, dtype: int64

In [19]:
# '데이터프레임변수'에서 '나이', '성별'열의 데이터만 가져오기
데이터프레임변수[['나이', '성별']]

나이 성별
1번  29  여
2번  24  남
3번  38  남
4번  31  여

In [20]:
데이터프레임변수[1:3]

이름  나이 성별
2번  이순신  24  남
3번  유관순  38  남

In [21]:
데이터프레임변수['2번':'3번']

이름  나이 성별
2번  이순신  24  남
3번  유관순  38  남

In [ ]:
# 파일 읽고 쓰기 위한 판다스 라이브러리를 가져오기
import pandas as pd
# data 경로의 train.csv 파일 가져오기
데이터 = pd.read_csv('./bigData-main/train.csvT')

# sklearn : 진짜 머신러닝하기


In [6]:
# train_test_split 함수를 가져오는 코드
from sklearn.model_selection import train_test_split
# DecisionTreeClassifier 함수를 가져오는 코드
from sklearn.tree import DecisionTreeClassifier

## numpy : 수학 계산하기
 - 벡터, 행렬 등 수치 연산을 수행하는 선형대수 라이브러리

In [9]:
import numpy as np
# 2행 3열의 행렬을 만들때 모두 0으로 채우기
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# 2행 3열의 행렬을 만들때 모두 1로 채우기
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# 2행, 3열의 행렬을 만들 때, 모두 10으로 채우기
np.full((2,3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [12]:
# 0부터 20개의 숫자 만들기
np.array(range(20))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
# 0부터 20개의 숫자로, 4행 5열의 행렬 만들기
np.array(range(20)).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 2.3 유용한 내장함수 활용하기

In [1]:
import pandas as pd
import numpy as np

# 나이, 성별로 이루어진 2차원 데이터, '\'는 여러줄에 작성하기 위한 기호
데이터 = { \
    '나이' : [20, 23, 49, 38, 32, 29, 25, 30, 32, 26], \
    '성별' : ['남', '여', '남', '여', '여', '여', '여', '여', '남', np.nan] \
}

In [2]:
# 생성한 딕셔너리 '데이터'를 DataFrame으로 변환하기
데이터 = pd.DataFrame(데이터)

In [21]:
데이터

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [22]:
type(데이터)

pandas.core.frame.DataFrame

In [25]:
데이터['나이'].sum()

304

In [26]:
sum(데이터['나이'])

304

In [27]:
데이터['나이'].max()

49

In [28]:
max(데이터['나이'])

49

In [29]:
데이터['나이'].min()

20

In [30]:
min(데이터['나이'])

20

In [31]:
데이터['나이'].mean()

30.4

In [32]:
데이터['나이'].median()

29.5

In [33]:
데이터['나이'].var()

69.15555555555557

In [34]:
데이터['나이'].std()

8.315981935740094

In [37]:
pow(데이터['나이'], 3)

0      8000
1     12167
2    117649
3     54872
4     32768
5     24389
6     15625
7     27000
8     32768
9     17576
Name: 나이, dtype: int64

In [38]:
데이터.quantile(0.25)


나이    25.25
Name: 0.25, dtype: float64

In [41]:
데이터.quantile(0.5)

나이    29.5
Name: 0.5, dtype: float64

In [42]:
데이터.quantile(0.75)

나이    32.0
Name: 0.75, dtype: float64

In [43]:
데이터.quantile(1)

나이    49.0
Name: 1.0, dtype: float64

In [47]:
round(데이터['나이']/7)

0    3.0
1    3.0
2    7.0
3    5.0
4    5.0
5    4.0
6    4.0
7    4.0
8    5.0
9    4.0
Name: 나이, dtype: float64

In [48]:
round(데이터['나이']/7, 2)

0    2.86
1    3.29
2    7.00
3    5.43
4    4.57
5    4.14
6    3.57
7    4.29
8    4.57
9    3.71
Name: 나이, dtype: float64

In [5]:
데이터.shape

(10, 2)

In [6]:
len(데이터)

10

In [7]:
len('Superman')

8

In [8]:
len('1234567890')

10

In [10]:
len(str(123)) # 숫자형은 str()함수로 형변환 해줘야 한다

3

In [11]:
데이터.size

20

In [12]:
데이터.head()

나이 성별
0  20  남
1  23  여
2  49  남
3  38  여
4  32  여

In [13]:
데이터.head(2)

나이 성별
0  20  남
1  23  여

In [14]:
데이터.tail()

나이   성별
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [15]:
데이터.tail(2)

나이   성별
8  32    남
9  26  NaN

In [16]:
데이터.columns

Index(['나이', '성별'], dtype='object')

In [17]:
데이터.index

RangeIndex(start=0, stop=10, step=1)

In [18]:
데이터['성별'].value_counts()

여    6
남    3
Name: 성별, dtype: int64

In [19]:
데이터.value_counts()

나이  성별
20  남     1
23  여     1
25  여     1
29  여     1
30  여     1
32  남     1
    여     1
38  여     1
49  남     1
dtype: int64

In [20]:
데이터['성별'].unique()

array(['남', '여', nan], dtype=object)

In [21]:
데이터.isnull()

나이     성별
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False
5  False  False
6  False  False
7  False  False
8  False  False
9  False   True

In [22]:
데이터['성별'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: 성별, dtype: bool

In [23]:
sum(데이터['성별'].isnull())

1

In [24]:
데이터.count()

나이    10
성별     9
dtype: int64

In [26]:
'I am superman!'.count('a')

2

In [27]:
데이터.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   나이      10 non-null     int64 
 1   성별      9 non-null      object
dtypes: int64(1), object(1)
memory usage: 288.0+ bytes


In [29]:
데이터.describe()

나이
count  10.000000
mean   30.400000
std     8.315982
min    20.000000
25%    25.250000
50%    29.500000
75%    32.000000
max    49.000000

In [30]:
데이터

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [31]:
데이터.transpose()

0   1   2   3   4   5   6   7   8    9
나이  20  23  49  38  32  29  25  30  32   26
성별   남   여   남   여   여   여   여   여   남  NaN

In [32]:
데이터.T

0   1   2   3   4   5   6   7   8    9
나이  20  23  49  38  32  29  25  30  32   26
성별   남   여   남   여   여   여   여   여   남  NaN

In [34]:
데이터.T[0]

나이    20
성별     남
Name: 0, dtype: object

In [35]:
데이터.T.index

Index(['나이', '성별'], dtype='object')

In [36]:
데이터.loc[3]

나이    38
성별     여
Name: 3, dtype: object

In [41]:
데이터.loc[:, '성별']

0      남
1      여
2      남
3      여
4      여
5      여
6      여
7      여
8      남
9    NaN
Name: 성별, dtype: object

In [42]:
데이터.loc[3:7]


나이 성별
3  38  여
4  32  여
5  29  여
6  25  여
7  30  여

In [43]:
데이터.loc[:, '성별']

0      남
1      여
2      남
3      여
4      여
5      여
6      여
7      여
8      남
9    NaN
Name: 성별, dtype: object

In [44]:
데이터.loc[:, ['나이', '성별']]

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [45]:
데이터.loc[3:7, '성별']

3    여
4    여
5    여
6    여
7    여
Name: 성별, dtype: object

In [46]:
데이터['성별']=='남'

0     True
1    False
2     True
3    False
4    False
5    False
6    False
7    False
8     True
9    False
Name: 성별, dtype: bool

In [47]:
데이터.loc[데이터['성별']=='남']

나이 성별
0  20  남
2  49  남
8  32  남

In [48]:
데이터.iloc[3]

나이    38
성별     여
Name: 3, dtype: object

In [49]:
데이터.iloc[0]

나이    20
성별     남
Name: 0, dtype: object

In [50]:
데이터.iloc[4:8]

나이 성별
4  32  여
5  29  여
6  25  여
7  30  여

In [51]:
데이터.iloc[:, 1]

0      남
1      여
2      남
3      여
4      여
5      여
6      여
7      여
8      남
9    NaN
Name: 성별, dtype: object

In [52]:
데이터.iloc[:, 0:2]

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [53]:
데이터.iloc[2, 1]

'남'

In [54]:
데이터.iloc[3:7, 1]

3    여
4    여
5    여
6    여
Name: 성별, dtype: object

In [55]:
데이터.sort_values('나이')

나이   성별
0  20    남
1  23    여
6  25    여
9  26  NaN
5  29    여
7  30    여
4  32    여
8  32    남
3  38    여
2  49    남

In [56]:
데이터.sort_values('나이', ascending=False)

나이   성별
2  49    남
3  38    여
4  32    여
8  32    남
7  30    여
5  29    여
9  26  NaN
6  25    여
1  23    여
0  20    남

In [57]:
데이터.sort_values(['나이', '성별'])

나이   성별
0  20    남
1  23    여
6  25    여
9  26  NaN
5  29    여
7  30    여
8  32    남
4  32    여
3  38    여
2  49    남

In [59]:
데이터

나이   성별
0  20    남
1  23    여
2  49    남
3  38    여
4  32    여
5  29    여
6  25    여
7  30    여
8  32    남
9  26  NaN

In [60]:
데이터['성별'].fillna('남')

0    남
1    여
2    남
3    여
4    여
5    여
6    여
7    여
8    남
9    남
Name: 성별, dtype: object

In [61]:
데이터['성별2'] = 데이터['성별'].fillna('남')

In [62]:
데이터

나이   성별 성별2
0  20    남   남
1  23    여   여
2  49    남   남
3  38    여   여
4  32    여   여
5  29    여   여
6  25    여   여
7  30    여   여
8  32    남   남
9  26  NaN   남

In [63]:
데이터

나이   성별 성별2
0  20    남   남
1  23    여   여
2  49    남   남
3  38    여   여
4  32    여   여
5  29    여   여
6  25    여   여
7  30    여   여
8  32    남   남
9  26  NaN   남

In [64]:
데이터.dropna()

나이 성별 성별2
0  20  남   남
1  23  여   여
2  49  남   남
3  38  여   여
4  32  여   여
5  29  여   여
6  25  여   여
7  30  여   여
8  32  남   남

In [65]:
데이터2 = 데이터.dropna()

In [66]:
데이터2

나이 성별 성별2
0  20  남   남
1  23  여   여
2  49  남   남
3  38  여   여
4  32  여   여
5  29  여   여
6  25  여   여
7  30  여   여
8  32  남   남

In [67]:
데이터.head()

나이 성별 성별2
0  20  남   남
1  23  여   여
2  49  남   남
3  38  여   여
4  32  여   여

In [70]:
데이터.drop(index=[0, 2, 4, 6, 8])

나이   성별 성별2
1  23    여   여
3  38    여   여
5  29    여   여
7  30    여   여
9  26  NaN   남

In [71]:
데이터.drop(columns = ['성별'])


나이 성별2
0  20   남
1  23   여
2  49   남
3  38   여
4  32   여
5  29   여
6  25   여
7  30   여
8  32   남
9  26   남

In [72]:
데이터['성별'].replace('여', 'F').replace('남', 'M')

0      M
1      F
2      M
3      F
4      F
5      F
6      F
7      F
8      M
9    NaN
Name: 성별, dtype: object

In [73]:
데이터

나이   성별 성별2
0  20    남   남
1  23    여   여
2  49    남   남
3  38    여   여
4  32    여   여
5  29    여   여
6  25    여   여
7  30    여   여
8  32    남   남
9  26  NaN   남