In [2]:
import numpy as np
x = np.arange(10).reshape(-1, 1)
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [3]:
y = 2*x + 1
y

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

In [4]:
# 임포트
from sklearn.linear_model import LinearRegression
# 모델 객체 생성
model = LinearRegression()
# 학습
model.fit(x,y)
# 예측
pred = model.predict([[10], [20]])

In [5]:
pred

array([[21.],
       [41.]])

In [7]:
# 임포트
from sklearn.svm import SVR
# 모델 객체 생성
model = SVR()
# 학습
model.fit(x,y)
# 예측
pred = model.predict([[10], [20]])
# 사이킷런이 대부분의 코드를 정형화시켜놓았음

E:\kdigital_a\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
